[profile.default]
src = "contracts"
out = "out"
libs = ["lib"]
test = "tests/foundry"
cache_path = "cache/foundry"

# Solidity compiler settings
solc = "0.8.28"
optimizer = true
optimizer_runs = 200
via_ir = true

# Test settings
verbosity = 2
gas_reports = ["*"]
gas_price = 1000000000  # 1 gwei

# Fuzz testing configuration
fuzz_runs = 1000
fuzz_max_test_rejects = 100000
fuzz_seed = "0x1234567890abcdef"

# Invariant testing settings
invariant_runs = 256
invariant_depth = 15
invariant_fail_on_revert = true
invariant_call_override = false

# RPC endpoints
[rpc_endpoints]
localhost = "http://127.0.0.1:8545"

# Formatter settings
[fmt]
line_length = 120
tab_width = 4
bracket_spacing = true
int_types = "long"

# Gas limit settings
gas_limit = 30000000 